import random
print ("This is our small program for the quiz")

print ("Not a 'Hello, World!' program")
userNumber = int(input("Enter a number between 1 and 10\n"))
rng = random.randint(1, 10)
newNumber = rng + userNumber
text = f"Your new number, which is generated by taking your provided number, '{number}', and using a randomly generated number, '{rng}', and adding them together, is '{newNumber}'"
print(text)